language: php
services:
  - mysql
before_install:
  - sudo apt-get -y install poppler-utils
php:
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"
before_script:
  - lib/createdb.sh -u root -c test/options.php --batch --no-password-file
  - lib/createdb.sh -u root -c test/cdb-options.php --no-dbuser --batch --no-password-file
script:
  - test/check.sh
